---
- name: create user accounts for all our servers
  hosts: all
  become: true
  remote_user: sysadmin
  vars_files:
    - password.yml
  tasks:
    - name: Removing user from secret.yml
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: true
